# https://circleci.com/docs/2.0/language-javascript/
version: 2
jobs:
  "node-8":
    docker:
      - image: circleci/node:8@sha256:69ff0a0e9de36672e9879c42a4767add991e19321d0b29adf5539786a6ee55ac
    working_directory: ~/typescript-starter
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
  "node-latest":
    docker:
      - image: circleci/node:latest@sha256:156d2e007d67a181d84d40e3d64bd63f6de02c0a2d57fa44f1ee860072a9140a
    working_directory: ~/typescript-starter
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

workflows:
  version: 2
  build:
    jobs:
      - "node-8"
      - "node-latest"